### ISSUE TITLE
[work-plan] Add LSP support

### ISSUE THREAD

**Issue by SamChou19815** [SamChou19815/samlang#18]
- [x] Migrate all command line options into configuration file #14
- [x] Support incremental type checking #15
- [x] Add type query service #16
- [x] Add auto completion service #17
- [x] Introduce [LSP dependency](https://github.com/eclipse/lsp4j)
- [x] Implement LSP server basics
- [x] Implement type query in LSP
- [x] Implement auto completion in LSP
- [x] Make VSCode extension talk to LSP
- [x] Publish new VSCode extension

**Comment by SamChou19815** [comment]
Done!
