### ISSUE TITLE
[lsp] Help improve samlang language server and win swags

### ISSUE THREAD

**Issue by SamChou19815** [SamChou19815/samlang#82]
## Swags

Successful completion of a task can win you a swag of your choice under $60 at https://github.myshopify.com/collections/all-products. :eyes:

## Tasks

For LSP Spec, see https://microsoft.github.io/language-server-protocol/specifications/specification-current/

- [x] [easy] Support "folding range" LSP command @ayshiff 
- [x] [medium] Support "goto definitions" LSP command @SamChou19815
  - [x] Goto definition for functions, methods (#134, @SamChou19815)
  - [x] Goto definition for class (#135, @SamChou19815)
  - [x] Goto definition for field access (#136 @SamChou19815)
  - [x] Goto definition for normal variables (#137, @SamChou19815)
- [x] [hard] Make pretty print keep comments (@SamChou19815)
- [x] [hard] Support "rename" LSP command (#503, #504, #505, @SamChou19815)

**Comment by ayshiff** [comment]
Hey @SamChou19815 !
I would like to help ! Can I start working on a task ? 👍

**Comment by SamChou19815** [comment]
@ayshiff yes, pick whatever one you like to do and I can add (@ayshiff) next to the item you picked.

**Comment by ayshiff** [comment]
> @ayshiff yes, pick whatever one you like to do and I can add (@ayshiff) next to the item you picked.

I'll take the first one then ! "Support "folding range" LSP command"

**Comment by SamChou19815** [comment]
All done!
